# -*- coding: utf-8 -*-
"""hack1 sharpe 0.4554 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QBn877gLC8bQvP_RtWy7GIFaGj7znnt1
"""

import pandas as pd
import numpy as np
import datetime

class TradingStrategy:
    def __init__(self, rebalancing_frequency="ME", initial_capital=10000000,
                 start_date=datetime.datetime(2010,1,4), end_date=datetime.datetime(2023,12,29)):
        self.rebalancing_frequency = rebalancing_frequency
        self.initial_capital = float(initial_capital)
        self.start_date = start_date
        self.end_date = end_date
        self.commission = 0.0005  # Reduced transaction costs
        self.slippage = 0.0003    # Reduced slippage
        self.risk_free_rate = 0.05  # Annual risk-free rate

        self.load_pricing_data()
        self.initialize_data_structures()

    def load_pricing_data(self):
        self.prices = pd.read_csv("Prices.csv", index_col='Date', parse_dates=True)
        self.returns = self.prices.pct_change().dropna()

    def initialize_data_structures(self):
        index = self.prices.index
        columns = self.prices.columns
        self.trades = pd.DataFrame(columns=['Ticker','Date','Price','n_shares_traded','Signal'])
        self.n_shares_position = pd.DataFrame(0, index=index, columns=columns, dtype=np.float64)
        self.position_amount = pd.DataFrame(0.0, index=index, columns=list(columns) + ["Cash"])
        self.position_amount.loc[self.prices.index[0], 'Cash'] = self.initial_capital
        self.position_long_short = pd.DataFrame(0, index=index, columns=columns)

    def optimize_portfolio(self, returns, min_lookback=6):
        recent_returns = returns.iloc[-min_lookback*21:] if len(returns) >= min_lookback*21 else returns
        mean_returns = recent_returns.mean()
        std_returns = recent_returns.std().replace(0, np.nan)
        sharpe_ratios = mean_returns / std_returns
        sharpe_ratios = sharpe_ratios.replace([np.nan, np.inf, -np.inf], 0)

        abs_sharpe = sharpe_ratios.abs()
        ranked_stocks = abs_sharpe.sort_values(ascending=False)

        weights = pd.Series(0.0, index=returns.columns)
        total_long, total_short = 0.0, 0.0

        # Improved allocation with dynamic exposure control
        for ticker in ranked_stocks.index:
            if total_long + total_short >= 0.95:
                break

            sr = sharpe_ratios[ticker]
            max_alloc = min(0.05, 0.05 * (abs_sharpe[ticker]/abs_sharpe.max()))

            if sr > 0:
                alloc = min(max_alloc, 0.55 - total_long, 0.95 - total_short - total_long)
                weights[ticker] = alloc
                total_long += alloc
            elif sr < 0:
                alloc = min(max_alloc, 0.95 - total_long - total_short)
                weights[ticker] = -alloc
                total_short += alloc

            # Enforce max 10% net exposure dynamically
            current_net = total_long - total_short
            if current_net > 0.10:
                reduce_by = current_net - 0.10
                long_tickers = weights[weights > 0].index
                if len(long_tickers) > 0:
                    reduction = reduce_by / len(long_tickers)
                    weights[long_tickers] -= reduction
                    total_long -= reduce_by

        return weights

    def calculate_sharpe(self, portfolio_values):
        # Use simple returns for negative value safety
        daily_returns = portfolio_values.pct_change().dropna()
        monthly_returns = daily_returns.resample('ME').apply(lambda x: (1 + x).prod() - 1)
        rf_monthly = (1 + self.risk_free_rate)**(1/12) - 1
        excess_returns = monthly_returns - rf_monthly
        annualized_sharpe = excess_returns.mean() * 12 / (monthly_returns.std() * np.sqrt(12))
        return annualized_sharpe

    def run_backtest(self):
        rebalancing_dates = pd.date_range(self.start_date, self.end_date,
                                        freq='ME' if self.rebalancing_frequency == "ME" else 'W-FRI')
        rebalancing_dates = rebalancing_dates.intersection(self.prices.index)

        trades_list = []

        for i, date in enumerate(self.prices.index):
            if i == 0:
                continue

            prev_date = self.prices.index[i-1]
            self.n_shares_position.loc[date] = self.n_shares_position.loc[prev_date]
            self.position_amount.loc[date] = self.position_amount.loc[prev_date]
            self.position_long_short.loc[date] = self.position_long_short.loc[prev_date]

            # Update positions with price changes
            for ticker in self.prices.columns:
                price = self.prices.loc[date, ticker]
                self.position_amount.loc[date, ticker] = self.n_shares_position.loc[date, ticker] * price

            # Check portfolio value to prevent negative NAV
            total_value = self.position_amount.loc[date].sum()
            if total_value <= 0:
                raise ValueError("Negative portfolio value detected - strategy failed")

            if date in rebalancing_dates:
                weights = self.optimize_portfolio(self.returns.loc[:date])
                total_value = self.position_amount.loc[date].sum()

                for ticker in self.prices.columns:
                    current_value = self.position_amount.loc[date, ticker]
                    target_value = weights[ticker] * total_value

                    if np.isclose(target_value, current_value, rtol=0.01):
                        continue

                    price = self.prices.loc[date, ticker]
                    price_adj = price * (1 + self.slippage * np.sign(weights[ticker]))

                    shares_diff = int((target_value - current_value) / price_adj)
                    if shares_diff == 0:
                        continue

                    # Apply transaction costs
                    trade_cost = abs(shares_diff * price_adj) * self.commission
                    self.position_amount.loc[date, 'Cash'] -= trade_cost

                    # Record trade
                    trades_list.append({
                        'Ticker': ticker,
                        'Date': date,
                        'Price': price_adj,
                        'n_shares_traded': abs(shares_diff),
                        'Signal': 1 if shares_diff > 0 else -1
                    })

                    # Update positions
                    self.n_shares_position.loc[date, ticker] += shares_diff
                    self.position_long_short.loc[date, ticker] = np.sign(self.n_shares_position.loc[date, ticker])

                    # Update cash position
                    self.position_amount.loc[date, 'Cash'] -= shares_diff * price_adj

        self.trades = pd.DataFrame(trades_list)
        portfolio_values = self.position_amount.sum(axis=1)

        # Handle remaining NaN values
        portfolio_values = portfolio_values.fillna(method='ffill').fillna(self.initial_capital)

        sharpe_ratio = self.calculate_sharpe(portfolio_values)
        print(f"Annualized Sharpe Ratio: {sharpe_ratio:.4f}")

if __name__ == "__main__":
    ts = TradingStrategy()
    ts.run_backtest()